log:
  format: "json"
aws:
  url: "https://localhost:9000"
  readypath: "/minio/health/ready"
  accessKey: "ElixirID"
  secretKey: "987654321"
  bucket: "test"
  region: "us-east-1"
  cacert: "./dev_utils/certs/ca.crt"

broker:
  host: "localhost"
  port: "5671"
  user: "test"
  password: "test"
  vhost: "/test"
  exchange: "localega.v1"
  routingKey: "files.inbox"
  ssl: "true"
  verifyPeer: "true"
  cacert: "./dev_utils/certs/ca.crt"
  clientCert: "./dev_utils/certs/client.crt"
  clientKey: "./dev_utils/certs/client.key"
# If the FQDN and hostname of the broker differ
# serverName can be set to the SAN name in the certificate
  #  serverName: ""

server:
  cert: "./dev_utils/certs/proxy.crt"
  key: "./dev_utils/certs/proxy.key"
  users: "./dev_utils/users.csv"
  jwtpubkeypath: "./dev_utils/keys/"
  jwtpubkeyurl: "https://login.elixir-czech.org/oidc/jwk"


