name: Functionality test
on: [push]
jobs:

  test:
    name: s3cmd
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20', '1.19']
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Run integration tests
        run: cd dev_utils && GOLANG_VERSION=${{ matrix.go-version }} docker-compose run integration_tests
