name: linting check
on: [push]
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.20', '1.19']
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@master
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.5.0
      with:
        args: -E bodyclose,gocritic,gofmt,gosec,govet,nestif,nlreturn,revive -e G107
