name: static check
on: [push, pull_request]
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check
      uses: nbisweden/golang-github-actions@v1.2.0
      with:
        run: lint

  imports:
    name: Imports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check
      uses: nbisweden/golang-github-actions@v1.2.0
      with:
        run: imports

  shadow:
    name: Shadow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check
      uses: nbisweden/golang-github-actions@v1.2.0
      with:
        run: shadow

  staticcheck:
    name: StaticCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check
      uses: nbisweden/golang-github-actions@v1.2.0
      with:
        run: staticcheck

  sec:
    name: Sec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check
      uses: nbisweden/golang-github-actions@v1.2.0
      with:
        run: sec
        flags: "-exclude=G107"
